#!/usr/bin/env python3
"""Regenerates the [patch.crates-io] block in .cargo/config.toml.

talos-agent depends directly on a handful of ROS 2 generated Rust message
crates (nav_msgs, geometry_msgs, ...). Those crates depend on each other
(e.g. geometry_msgs -> std_msgs, builtin_interfaces), so cargo needs a
[patch.crates-io] entry for the full transitive closure, not just the
crates talos-agent names directly. This script computes that closure from
the packages colcon actually built into rclrs_ws/install/ and rewrites
.cargo/config.toml accordingly, instead of hand-maintaining the list.
"""

import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INSTALL_DIR = ROOT / "rclrs_ws" / "install"
AGENT_MANIFEST = ROOT / "talos-agent" / "Cargo.toml"
OUTPUT = ROOT / ".cargo" / "config.toml"

HEADER = (
    "# AUTO-GENERATED by scripts/gen-cargo-patches.sh - do not hand edit.\n"
    "# Patches crates-io with locally built ROS 2 Rust packages from rclrs_ws.\n"
)


def crate_manifest(name: str) -> Path:
    return INSTALL_DIR / name / "share" / name / "rust" / "Cargo.toml"


def load_deps(name: str) -> set[str]:
    manifest = crate_manifest(name)
    if not manifest.is_file():
        return set()
    with manifest.open("rb") as f:
        data = tomllib.load(f)
    return set(data.get("dependencies", {}))


def main() -> None:
    with AGENT_MANIFEST.open("rb") as f:
        agent_deps = set(tomllib.load(f)["dependencies"])

    # Seed the closure with whichever direct deps are actually ROS-generated
    # crates (i.e. colcon built them into rclrs_ws/install/).
    roots = {name for name in agent_deps if crate_manifest(name).is_file()}
    if not roots:
        raise SystemExit(
            f"no ROS crates found among {AGENT_MANIFEST}'s dependencies "
            f"under {INSTALL_DIR} - has `pixi run build` been run in rclrs_ws?"
        )

    closure = set(roots)
    frontier = set(roots)
    while frontier:
        next_frontier: set[str] = set()
        for name in frontier:
            for dep in load_deps(name):
                if dep not in closure and crate_manifest(dep).is_file():
                    closure.add(dep)
                    next_frontier.add(dep)
        frontier = next_frontier

    lines = [HEADER]
    for name in sorted(closure):
        rel_path = crate_manifest(name).relative_to(ROOT).parent
        lines.append(f"[patch.crates-io.{name}]\n")
        lines.append(f'path = "{rel_path}"\n')
        lines.append("\n")

    OUTPUT.write_text("".join(lines).rstrip() + "\n")
    print(f"wrote {len(closure)} patch entries to {OUTPUT}")


if __name__ == "__main__":
    main()
